name: Build Image using Containerfile
on: [push]

env:
    IMAGE_NAME: docker-oci-workshop
    IMAGE_TAGS: v1 ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Build image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: docker-oci-workshop
        tags: branch-${{ github.ref_name}} ${{ github.sha }}
        containerfiles: ./example.containerfile
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      id: push
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust
    - name: Run the image
      run: docker run ghcr.io/joshuayoungg/docker-oci-workshop:4b6f5e69784b39cb197a4814b06547e341e8b560 -v ${{ github.workspace }}:/workspace -w /workspace build.bash
